INSERT INTO building VALUES (1, 'Weizmann Hall', 'Sokolov 67, Tel Aviv', 5, 379);
INSERT INTO building VALUES (2, 'Weizmann Hall', 'Jabotinsky 85, Beersheba', 5, 323);
INSERT INTO building VALUES (3, 'Shaked Hall', 'Ibn Gabirol 89, Beersheba', 5, 318);
INSERT INTO building VALUES (4, 'The Arava Tower', 'HaMasger 31, Jerusalem', 5, 333);
INSERT INTO building VALUES (5, 'Ben Gurion Towers', 'Sokolov 54, Tel Aviv', 3, 367);
INSERT INTO building VALUES (6, 'Jerusalem Heights', 'Ben Yehuda 63, Beersheba', 3, 141);
INSERT INTO building VALUES (7, 'Weizmann Hall', 'Ben Yehuda 12, Beersheba', 4, 80);
INSERT INTO building VALUES (8, 'Shaked Hall', 'Begin 43, Haifa', 5, 29);
INSERT INTO building VALUES (9, 'Shaked Hall', 'HaPalmach 37, Beersheba', 3, 329);
INSERT INTO building VALUES (10, 'Shamir Hall', 'Ben Gurion 11, Haifa', 3, 172);
INSERT INTO building VALUES (11, 'Golda Residence', 'Rothschild 28, Jerusalem', 4, 70);
INSERT INTO building VALUES (12, 'Peres House', 'Emek Refaim 5, Tel Aviv', 4, 224);
INSERT INTO building VALUES (13, 'Rabin House', 'Hertzel 43, Tel Aviv', 2, 101);
INSERT INTO building VALUES (14, 'Ben Gurion Towers', 'Dizengoff 74, Jerusalem', 4, 291);
INSERT INTO building VALUES (15, 'Ben Gurion Towers', 'Derech Hevron 55, Haifa', 5, 306);
INSERT INTO building VALUES (16, 'Shamir Hall', 'Eilat 57, Haifa', 5, 80);
INSERT INTO building VALUES (17, 'Shaked Hall', 'Shlomtzion HaMalka 5, Beersheba', 3, 299);
INSERT INTO building VALUES (18, 'Rabin House', 'Kaplan 53, Haifa', 3, 294);
INSERT INTO building VALUES (19, 'Ben Gurion Towers', 'Begin 23, Tel Aviv', 5, 83);
INSERT INTO building VALUES (20, 'Einstein Lodge', 'King George 30, Tel Aviv', 4, 1);
INSERT INTO building VALUES (21, 'Rabin House', 'Begin 27, Beersheba', 4, 259);
INSERT INTO building VALUES (22, 'Shamir Hall', 'Hertzel 3, Jerusalem', 3, 293);
INSERT INTO building VALUES (23, 'Golda Residence', 'Sokolov 76, Beersheba', 4, 396);
INSERT INTO building VALUES (24, 'Peres House', 'Ibn Gabirol 90, Beersheba', 3, 172);
INSERT INTO building VALUES (25, 'Shamir Hall', 'King George 90, Tel Aviv', 2, 266);
INSERT INTO building VALUES (26, 'Rabin House', 'HaPalmach 21, Jerusalem', 4, 15);
INSERT INTO building VALUES (27, 'Einstein Lodge', 'Sokolov 7, Beersheba', 5, 331);
INSERT INTO building VALUES (28, 'Weizmann Hall', 'Henrietta Szold 50, Haifa', 2, 18);
INSERT INTO building VALUES (29, 'Ben Gurion Towers', 'Herzl 66, Beersheba', 2, 76);
INSERT INTO building VALUES (30, 'Peres House', 'Jaffa 7, Beersheba', 2, 277);
INSERT INTO building VALUES (31, 'Peres House', 'Herzl 43, Beersheba', 2, 337);
INSERT INTO building VALUES (32, 'Jerusalem Heights', 'Herzl 52, Haifa', 5, 49);
INSERT INTO building VALUES (33, 'Herzl Residence', 'Yehuda Halevi 19, Tel Aviv', 4, 76);
INSERT INTO building VALUES (34, 'Herzl Residence', 'Ben Yehuda 38, Jerusalem', 5, 230);
INSERT INTO building VALUES (35, 'Herzl Residence', 'Arlozorov 48, Tel Aviv', 3, 284);
INSERT INTO building VALUES (36, 'Carmel Residence', 'HaMasger 30, Jerusalem', 3, 371);
INSERT INTO building VALUES (37, 'Galilee Residence', 'Hertzel 7, Beersheba', 4, 372);
INSERT INTO building VALUES (38, 'Herzl Residence', 'Herzl 77, Haifa', 3, 378);
INSERT INTO building VALUES (39, 'Shamir Hall', 'Herzl 87, Tel Aviv', 4, 107);
INSERT INTO building VALUES (40, 'Technion Heights', 'Herzl 97, Tel Aviv', 2, 19);
INSERT INTO building VALUES (41, 'Carmel Residence', 'Kaplan 73, Jerusalem', 3, 20);
INSERT INTO building VALUES (42, 'Golda Residence', 'Emek Refaim 39, Tel Aviv', 2, 285);
INSERT INTO building VALUES (43, 'Galilee Residence', 'Emek Refaim 80, Haifa', 5, 81);
INSERT INTO building VALUES (44, 'Ben Gurion Towers', 'Dizengoff 48, Jerusalem', 2, 205);
INSERT INTO building VALUES (45, 'Negev Hall', 'King George 51, Haifa', 4, 134);
INSERT INTO building VALUES (46, 'Rabin House', 'Eilat 33, Haifa', 2, 119);
INSERT INTO building VALUES (47, 'Rabin House', 'Emek Refaim 53, Tel Aviv', 2, 327);
INSERT INTO building VALUES (48, 'Carmel Residence', 'HaYarkon 64, Haifa', 5, 361);
INSERT INTO building VALUES (49, 'Einstein Lodge', 'HaPalmach 7, Tel Aviv', 3, 44);
INSERT INTO building VALUES (50, 'Ben Gurion Towers', 'Arlozorov 56, Beersheba', 3, 376);
INSERT INTO building VALUES (51, 'Negev Hall', 'Ben Yehuda 5, Tel Aviv', 3, 98);
INSERT INTO building VALUES (52, 'Herzl Residence', 'HaMasger 55, Jerusalem', 4, 390);
INSERT INTO building VALUES (53, 'Herzl Residence', 'Ibn Gabirol 91, Tel Aviv', 4, 214);
INSERT INTO building VALUES (54, 'Rabin House', 'Agron 96, Jerusalem', 2, 25);
INSERT INTO building VALUES (55, 'Rabin House', 'Allenby 85, Jerusalem', 3, 174);
INSERT INTO building VALUES (56, 'Herzl Residence', 'Sokolov 80, Haifa', 4, 54);
INSERT INTO building VALUES (57, 'Peres House', 'Jabotinsky 61, Beersheba', 3, 264);
INSERT INTO building VALUES (58, 'Galilee Residence', 'HaPalmach 91, Haifa', 5, 12);
INSERT INTO building VALUES (59, 'Galilee Residence', 'Kaplan 91, Tel Aviv', 4, 169);
INSERT INTO building VALUES (60, 'Ben Gurion Towers', 'HaYarkon 43, Tel Aviv', 4, 24);
INSERT INTO building VALUES (61, 'Einstein Lodge', 'Moriah 64, Haifa', 5, 362);
INSERT INTO building VALUES (62, 'Ben Gurion Towers', 'Hertzel 53, Tel Aviv', 2, 390);
INSERT INTO building VALUES (63, 'Weizmann Hall', 'Dizengoff 56, Tel Aviv', 3, 17);
INSERT INTO building VALUES (64, 'Weizmann Hall', 'HaYarkon 78, Jerusalem', 4, 177);
INSERT INTO building VALUES (65, 'Shamir Hall', 'Rothschild 20, Beersheba', 2, 92);
INSERT INTO building VALUES (66, 'Golda Residence', 'Yigal Alon 43, Tel Aviv', 3, 379);
INSERT INTO building VALUES (67, 'Golda Residence', 'Eilat 9, Haifa', 3, 271);
INSERT INTO building VALUES (68, 'Technion Heights', 'Allenby 72, Tel Aviv', 5, 30);
INSERT INTO building VALUES (69, 'Rabin House', 'Agron 94, Jerusalem', 4, 348);
INSERT INTO building VALUES (70, 'Negev Hall', 'HaYarkon 60, Tel Aviv', 3, 267);
INSERT INTO building VALUES (71, 'Carmel Residence', 'Hertzel 71, Haifa', 3, 317);
INSERT INTO building VALUES (72, 'Shamir Hall', 'Yehuda Halevi 96, Beersheba', 5, 234);
INSERT INTO building VALUES (73, 'Golda Residence', 'Yitzhak Rambo 6, Haifa', 3, 84);
INSERT INTO building VALUES (74, 'Shaked Hall', 'Hertzel 54, Jerusalem', 5, 105);
INSERT INTO building VALUES (75, 'Peres House', 'Jaffa 86, Beersheba', 2, 57);
INSERT INTO building VALUES (76, 'Herzl Residence', 'Yigal Alon 67, Beersheba', 3, 342);
INSERT INTO building VALUES (77, 'Shamir Hall', 'Allenby 57, Jerusalem', 2, 194);
INSERT INTO building VALUES (78, 'Galilee Residence', 'Eilat 42, Beersheba', 2, 221);
INSERT INTO building VALUES (79, 'Carmel Residence', 'Rothschild 68, Tel Aviv', 2, 224);
INSERT INTO building VALUES (80, 'Shaked Hall', 'Henrietta Szold 66, Jerusalem', 4, 106);
INSERT INTO building VALUES (81, 'Ben Gurion Towers', 'Moriah 33, Haifa', 2, 339);
INSERT INTO building VALUES (82, 'Weizmann Hall', 'Dizengoff 75, Beersheba', 3, 307);
INSERT INTO building VALUES (83, 'Carmel Residence', 'Ben Yehuda 71, Jerusalem', 4, 348);
INSERT INTO building VALUES (84, 'Golda Residence', 'HaPalmach 44, Beersheba', 3, 1);
INSERT INTO building VALUES (85, 'Jerusalem Heights', 'Kaplan 19, Haifa', 4, 179);
INSERT INTO building VALUES (86, 'The Arava Tower', 'Sokolov 7, Beersheba', 2, 19);
INSERT INTO building VALUES (87, 'Peres House', 'Henrietta Szold 41, Tel Aviv', 3, 6);
INSERT INTO building VALUES (88, 'Weizmann Hall', 'Hertzel 14, Beersheba', 3, 278);
INSERT INTO building VALUES (89, 'Jerusalem Heights', 'HaMasger 3, Haifa', 2, 51);
INSERT INTO building VALUES (90, 'Negev Hall', 'Rager Boulevard 15, Tel Aviv', 2, 99);
INSERT INTO building VALUES (91, 'Galilee Residence', 'Rager Boulevard 31, Tel Aviv', 3, 61);
INSERT INTO building VALUES (92, 'Shamir Hall', 'Rager Boulevard 80, Tel Aviv', 5, 327);
INSERT INTO building VALUES (93, 'Shamir Hall', 'HaYarkon 12, Tel Aviv', 4, 235);
INSERT INTO building VALUES (94, 'Einstein Lodge', 'Emek Refaim 65, Haifa', 5, 361);
INSERT INTO building VALUES (95, 'The Arava Tower', 'Yehuda Halevi 8, Tel Aviv', 3, 355);
INSERT INTO building VALUES (96, 'Shamir Hall', 'Agron 57, Haifa', 5, 400);
INSERT INTO building VALUES (97, 'The Arava Tower', 'Hertzel 14, Haifa', 5, 312);
INSERT INTO building VALUES (98, 'Einstein Lodge', 'Ben Gurion 5, Jerusalem', 2, 184);
INSERT INTO building VALUES (99, 'Shamir Hall', 'Ben Yehuda 7, Tel Aviv', 4, 38);
INSERT INTO building VALUES (100, 'Ben Gurion Towers', 'Rothschild 44, Beersheba', 4, 3);
INSERT INTO building VALUES (101, 'Einstein Lodge', 'Ben Gurion 27, Jerusalem', 4, 399);
INSERT INTO building VALUES (102, 'Carmel Residence', 'Sokolov 10, Tel Aviv', 5, 47);
INSERT INTO building VALUES (103, 'Ben Gurion Towers', 'Rager Boulevard 65, Beersheba', 2, 230);
INSERT INTO building VALUES (104, 'Herzl Residence', 'Jabotinsky 5, Tel Aviv', 4, 92);
INSERT INTO building VALUES (105, 'Jerusalem Heights', 'Jabotinsky 36, Jerusalem', 5, 334);
INSERT INTO building VALUES (106, 'Shamir Hall', 'Ben Yehuda 3, Beersheba', 5, 175);
INSERT INTO building VALUES (107, 'Negev Hall', 'Rothschild 48, Jerusalem', 3, 213);
INSERT INTO building VALUES (108, 'Carmel Residence', 'Ben Gurion 66, Beersheba', 2, 226);
INSERT INTO building VALUES (109, 'Negev Hall', 'Hertzel 62, Jerusalem', 5, 363);
INSERT INTO building VALUES (110, 'Galilee Residence', 'Dizengoff 68, Tel Aviv', 4, 9);
INSERT INTO building VALUES (111, 'Einstein Lodge', 'Ben Yehuda 90, Tel Aviv', 3, 113);
INSERT INTO building VALUES (112, 'Negev Hall', 'Arlozorov 31, Jerusalem', 5, 312);
INSERT INTO building VALUES (113, 'Negev Hall', 'Emek Refaim 39, Tel Aviv', 4, 196);
INSERT INTO building VALUES (114, 'Ben Gurion Towers', 'Yehuda Halevi 34, Jerusalem', 2, 258);
INSERT INTO building VALUES (115, 'Ben Gurion Towers', 'Henrietta Szold 92, Tel Aviv', 5, 87);
INSERT INTO building VALUES (116, 'Peres House', 'Ben Gurion 28, Jerusalem', 4, 246);
INSERT INTO building VALUES (117, 'Shamir Hall', 'Ben Yehuda 74, Jerusalem', 5, 117);
INSERT INTO building VALUES (118, 'Galilee Residence', 'Ben Gurion 45, Beersheba', 2, 250);
INSERT INTO building VALUES (119, 'Weizmann Hall', 'Weizmann 98, Tel Aviv', 4, 59);
INSERT INTO building VALUES (120, 'Jerusalem Heights', 'Ibn Gabirol 85, Beersheba', 3, 209);
INSERT INTO building VALUES (121, 'Rabin House', 'Shlomtzion HaMalka 13, Tel Aviv', 3, 27);
INSERT INTO building VALUES (122, 'Weizmann Hall', 'Rager Boulevard 31, Haifa', 4, 26);
INSERT INTO building VALUES (123, 'Shamir Hall', 'Dizengoff 77, Beersheba', 3, 292);
INSERT INTO building VALUES (124, 'Shamir Hall', 'Jaffa 27, Jerusalem', 3, 346);
INSERT INTO building VALUES (125, 'Einstein Lodge', 'Yitzhak Rambo 29, Beersheba', 2, 102);
INSERT INTO building VALUES (126, 'Carmel Residence', 'Rothschild 66, Beersheba', 5, 289);
INSERT INTO building VALUES (127, 'Ben Gurion Towers', 'Dizengoff 31, Beersheba', 3, 44);
INSERT INTO building VALUES (128, 'Galilee Residence', 'Hertzel 48, Haifa', 2, 74);
INSERT INTO building VALUES (129, 'Einstein Lodge', 'Weizmann 22, Beersheba', 3, 179);
INSERT INTO building VALUES (130, 'Herzl Residence', 'HaPalmach 42, Jerusalem', 5, 102);
INSERT INTO building VALUES (131, 'Shaked Hall', 'Herzl 31, Tel Aviv', 3, 64);
INSERT INTO building VALUES (132, 'Herzl Residence', 'Hertzel 42, Tel Aviv', 2, 238);
INSERT INTO building VALUES (133, 'Carmel Residence', 'Jaffa 86, Jerusalem', 5, 159);
INSERT INTO building VALUES (134, 'The Arava Tower', 'Ben Gurion 33, Jerusalem', 3, 195);
INSERT INTO building VALUES (135, 'Jerusalem Heights', 'Rothschild 26, Beersheba', 4, 334);
INSERT INTO building VALUES (136, 'Carmel Residence', 'Dizengoff 15, Tel Aviv', 3, 127);
INSERT INTO building VALUES (137, 'Galilee Residence', 'Hertzel 28, Tel Aviv', 5, 329);
INSERT INTO building VALUES (138, 'Herzl Residence', 'Jabotinsky 29, Haifa', 4, 346);
INSERT INTO building VALUES (139, 'Galilee Residence', 'Hertzel 38, Beersheba', 2, 135);
INSERT INTO building VALUES (140, 'Galilee Residence', 'Ben Yehuda 77, Beersheba', 2, 160);
INSERT INTO building VALUES (141, 'Carmel Residence', 'Rager Boulevard 95, Haifa', 4, 321);
INSERT INTO building VALUES (142, 'Rabin House', 'Rothschild 67, Beersheba', 5, 232);
INSERT INTO building VALUES (143, 'Carmel Residence', 'Moriah 91, Beersheba', 2, 193);
INSERT INTO building VALUES (144, 'The Arava Tower', 'Rothschild 92, Beersheba', 5, 196);
INSERT INTO building VALUES (145, 'Jerusalem Heights', 'Shlomtzion HaMalka 42, Tel Aviv', 4, 317);
INSERT INTO building VALUES (146, 'Weizmann Hall', 'Weizmann 79, Jerusalem', 5, 4);
INSERT INTO building VALUES (147, 'Jerusalem Heights', 'Henrietta Szold 2, Jerusalem', 2, 95);
INSERT INTO building VALUES (148, 'Peres House', 'HaPalmach 49, Haifa', 5, 97);
INSERT INTO building VALUES (149, 'Jerusalem Heights', 'Jabotinsky 59, Tel Aviv', 5, 340);
INSERT INTO building VALUES (150, 'Shamir Hall', 'Shlomtzion HaMalka 63, Jerusalem', 2, 362);
INSERT INTO building VALUES (151, 'Shaked Hall', 'Herzl 46, Beersheba', 2, 299);
INSERT INTO building VALUES (152, 'Rabin House', 'Emek Refaim 94, Jerusalem', 5, 141);
INSERT INTO building VALUES (153, 'Peres House', 'Rager Boulevard 17, Beersheba', 5, 154);
INSERT INTO building VALUES (154, 'Golda Residence', 'HaYarkon 48, Beersheba', 3, 13);
INSERT INTO building VALUES (155, 'Einstein Lodge', 'Rothschild 60, Beersheba', 2, 50);
INSERT INTO building VALUES (156, 'Jerusalem Heights', 'Hertzel 61, Jerusalem', 4, 132);
INSERT INTO building VALUES (157, 'Herzl Residence', 'Jabotinsky 27, Haifa', 4, 135);
INSERT INTO building VALUES (158, 'Herzl Residence', 'Eilat 28, Tel Aviv', 5, 191);
INSERT INTO building VALUES (159, 'Weizmann Hall', 'Yigal Alon 5, Haifa', 4, 193);
INSERT INTO building VALUES (160, 'Golda Residence', 'Agron 25, Jerusalem', 5, 388);
INSERT INTO building VALUES (161, 'Peres House', 'Herzl 17, Jerusalem', 3, 203);
INSERT INTO building VALUES (162, 'Weizmann Hall', 'Rothschild 97, Beersheba', 4, 316);
INSERT INTO building VALUES (163, 'Negev Hall', 'Rager Boulevard 54, Jerusalem', 3, 254);
INSERT INTO building VALUES (164, 'Ben Gurion Towers', 'HaPalmach 89, Haifa', 2, 327);
INSERT INTO building VALUES (165, 'Rabin House', 'Arlozorov 36, Tel Aviv', 2, 235);
INSERT INTO building VALUES (166, 'The Arava Tower', 'Begin 65, Beersheba', 4, 309);
INSERT INTO building VALUES (167, 'Carmel Residence', 'Dizengoff 96, Beersheba', 4, 368);
INSERT INTO building VALUES (168, 'Galilee Residence', 'Rothschild 85, Tel Aviv', 2, 96);
INSERT INTO building VALUES (169, 'Herzl Residence', 'Rager Boulevard 63, Beersheba', 4, 193);
INSERT INTO building VALUES (170, 'The Arava Tower', 'Henrietta Szold 48, Haifa', 3, 341);
INSERT INTO building VALUES (171, 'Ben Gurion Towers', 'Dizengoff 59, Tel Aviv', 2, 142);
INSERT INTO building VALUES (172, 'Golda Residence', 'Moriah 25, Haifa', 2, 323);
INSERT INTO building VALUES (173, 'Weizmann Hall', 'King George 32, Jerusalem', 4, 131);
INSERT INTO building VALUES (174, 'Technion Heights', 'Jaffa 67, Haifa', 4, 221);
INSERT INTO building VALUES (175, 'Weizmann Hall', 'Yitzhak Rambo 96, Beersheba', 5, 146);
INSERT INTO building VALUES (176, 'Shamir Hall', 'Rothschild 78, Haifa', 2, 295);
INSERT INTO building VALUES (177, 'The Arava Tower', 'King George 16, Haifa', 2, 378);
INSERT INTO building VALUES (178, 'The Arava Tower', 'HaPalmach 48, Beersheba', 4, 319);
INSERT INTO building VALUES (179, 'Jerusalem Heights', 'Herzl 90, Jerusalem', 4, 320);
INSERT INTO building VALUES (180, 'The Arava Tower', 'Dizengoff 6, Beersheba', 5, 299);
INSERT INTO building VALUES (181, 'Negev Hall', 'Ben Yehuda 18, Beersheba', 3, 344);
INSERT INTO building VALUES (182, 'Herzl Residence', 'Emek Refaim 78, Tel Aviv', 4, 112);
INSERT INTO building VALUES (183, 'Weizmann Hall', 'HaYarkon 38, Jerusalem', 3, 7);
INSERT INTO building VALUES (184, 'The Arava Tower', 'Agron 78, Haifa', 4, 368);
INSERT INTO building VALUES (185, 'Golda Residence', 'Yitzhak Rambo 91, Beersheba', 5, 333);
INSERT INTO building VALUES (186, 'Technion Heights', 'Jaffa 79, Jerusalem', 3, 387);
INSERT INTO building VALUES (187, 'Herzl Residence', 'Jabotinsky 21, Jerusalem', 4, 323);
INSERT INTO building VALUES (188, 'Jerusalem Heights', 'Henrietta Szold 28, Jerusalem', 4, 86);
INSERT INTO building VALUES (189, 'The Arava Tower', 'Sokolov 51, Haifa', 3, 113);
INSERT INTO building VALUES (190, 'Shamir Hall', 'Emek Refaim 11, Beersheba', 3, 69);
INSERT INTO building VALUES (191, 'Herzl Residence', 'Sokolov 80, Beersheba', 4, 386);
INSERT INTO building VALUES (192, 'Technion Heights', 'King George 73, Haifa', 3, 233);
INSERT INTO building VALUES (193, 'Einstein Lodge', 'Yitzhak Rambo 16, Jerusalem', 4, 91);
INSERT INTO building VALUES (194, 'Peres House', 'Yigal Alon 19, Haifa', 2, 194);
INSERT INTO building VALUES (195, 'Shaked Hall', 'King George 45, Jerusalem', 4, 185);
INSERT INTO building VALUES (196, 'Peres House', 'Derech Hevron 63, Jerusalem', 2, 29);
INSERT INTO building VALUES (197, 'Peres House', 'Rothschild 83, Beersheba', 4, 368);
INSERT INTO building VALUES (198, 'Jerusalem Heights', 'Emek Refaim 46, Haifa', 4, 62);
INSERT INTO building VALUES (199, 'Technion Heights', 'HaPalmach 91, Tel Aviv', 3, 212);
INSERT INTO building VALUES (200, 'Peres House', 'Ben Yehuda 87, Tel Aviv', 4, 323);
INSERT INTO building VALUES (201, 'Jerusalem Heights', 'Henrietta Szold 71, Tel Aviv', 3, 180);
INSERT INTO building VALUES (202, 'Negev Hall', 'HaYarkon 51, Beersheba', 3, 68);
INSERT INTO building VALUES (203, 'Negev Hall', 'King George 31, Haifa', 2, 69);
INSERT INTO building VALUES (204, 'Jerusalem Heights', 'Jaffa 76, Beersheba', 5, 292);
INSERT INTO building VALUES (205, 'Rabin House', 'Weizmann 9, Tel Aviv', 3, 143);
INSERT INTO building VALUES (206, 'Herzl Residence', 'Yehuda Halevi 49, Beersheba', 2, 65);
INSERT INTO building VALUES (207, 'Technion Heights', 'Rager Boulevard 73, Jerusalem', 5, 218);
INSERT INTO building VALUES (208, 'Technion Heights', 'Ben Gurion 42, Jerusalem', 2, 262);
INSERT INTO building VALUES (209, 'Galilee Residence', 'Ben Gurion 26, Tel Aviv', 5, 26);
INSERT INTO building VALUES (210, 'Galilee Residence', 'Moriah 21, Haifa', 2, 185);
INSERT INTO building VALUES (211, 'Herzl Residence', 'Begin 13, Jerusalem', 2, 213);
INSERT INTO building VALUES (212, 'Weizmann Hall', 'Yitzhak Rambo 91, Beersheba', 4, 54);
INSERT INTO building VALUES (213, 'Herzl Residence', 'HaMasger 37, Jerusalem', 3, 153);
INSERT INTO building VALUES (214, 'Peres House', 'Kaplan 2, Haifa', 4, 108);
INSERT INTO building VALUES (215, 'Herzl Residence', 'Eilat 72, Beersheba', 3, 82);
INSERT INTO building VALUES (216, 'Negev Hall', 'Yitzhak Rambo 73, Jerusalem', 4, 258);
INSERT INTO building VALUES (217, 'Golda Residence', 'Agron 28, Jerusalem', 2, 267);
INSERT INTO building VALUES (218, 'Carmel Residence', 'Yehuda Halevi 63, Haifa', 4, 12);
INSERT INTO building VALUES (219, 'Einstein Lodge', 'Jabotinsky 19, Tel Aviv', 2, 236);
INSERT INTO building VALUES (220, 'Carmel Residence', 'Ibn Gabirol 68, Tel Aviv', 2, 266);
INSERT INTO building VALUES (221, 'Peres House', 'Yitzhak Rambo 79, Tel Aviv', 5, 151);
INSERT INTO building VALUES (222, 'Ben Gurion Towers', 'Allenby 13, Beersheba', 5, 144);
INSERT INTO building VALUES (223, 'Golda Residence', 'HaMasger 79, Tel Aviv', 5, 336);
INSERT INTO building VALUES (224, 'Jerusalem Heights', 'HaPalmach 32, Tel Aviv', 2, 41);
INSERT INTO building VALUES (225, 'Golda Residence', 'Ibn Gabirol 71, Beersheba', 2, 271);
INSERT INTO building VALUES (226, 'Ben Gurion Towers', 'Emek Refaim 58, Jerusalem', 4, 243);
INSERT INTO building VALUES (227, 'Golda Residence', 'Arlozorov 21, Beersheba', 5, 135);
INSERT INTO building VALUES (228, 'Jerusalem Heights', 'Emek Refaim 89, Beersheba', 4, 3);
INSERT INTO building VALUES (229, 'Carmel Residence', 'Shlomtzion HaMalka 95, Haifa', 5, 224);
INSERT INTO building VALUES (230, 'Ben Gurion Towers', 'Jaffa 63, Tel Aviv', 5, 262);
INSERT INTO building VALUES (231, 'Ben Gurion Towers', 'Emek Refaim 46, Beersheba', 4, 121);
INSERT INTO building VALUES (232, 'Galilee Residence', 'Shlomtzion HaMalka 78, Beersheba', 3, 74);
INSERT INTO building VALUES (233, 'Shaked Hall', 'HaYarkon 21, Beersheba', 4, 6);
INSERT INTO building VALUES (234, 'Einstein Lodge', 'Henrietta Szold 68, Haifa', 2, 1);
INSERT INTO building VALUES (235, 'Weizmann Hall', 'Emek Refaim 46, Jerusalem', 2, 232);
INSERT INTO building VALUES (236, 'The Arava Tower', 'Ibn Gabirol 10, Beersheba', 3, 87);
INSERT INTO building VALUES (237, 'Weizmann Hall', 'Derech Hevron 17, Tel Aviv', 3, 257);
INSERT INTO building VALUES (238, 'Technion Heights', 'HaYarkon 14, Jerusalem', 3, 23);
INSERT INTO building VALUES (239, 'Shamir Hall', 'Hertzel 96, Jerusalem', 2, 285);
INSERT INTO building VALUES (240, 'Technion Heights', 'HaYarkon 35, Beersheba', 4, 70);
INSERT INTO building VALUES (241, 'Herzl Residence', 'Ibn Gabirol 83, Tel Aviv', 3, 279);
INSERT INTO building VALUES (242, 'Jerusalem Heights', 'Rager Boulevard 36, Tel Aviv', 4, 379);
INSERT INTO building VALUES (243, 'The Arava Tower', 'Rothschild 79, Beersheba', 3, 116);
INSERT INTO building VALUES (244, 'Golda Residence', 'King George 82, Beersheba', 4, 240);
INSERT INTO building VALUES (245, 'Shamir Hall', 'Eilat 60, Jerusalem', 3, 3);
INSERT INTO building VALUES (246, 'Shaked Hall', 'Emek Refaim 67, Beersheba', 5, 262);
INSERT INTO building VALUES (247, 'Shamir Hall', 'HaYarkon 1, Jerusalem', 4, 121);
INSERT INTO building VALUES (248, 'Shaked Hall', 'Begin 87, Jerusalem', 4, 224);
INSERT INTO building VALUES (249, 'Shamir Hall', 'Herzl 25, Beersheba', 3, 31);
INSERT INTO building VALUES (250, 'The Arava Tower', 'Weizmann 98, Beersheba', 3, 226);
INSERT INTO building VALUES (251, 'Weizmann Hall', 'Emek Refaim 88, Jerusalem', 5, 392);
INSERT INTO building VALUES (252, 'Carmel Residence', 'Jaffa 15, Jerusalem', 5, 183);
INSERT INTO building VALUES (253, 'Carmel Residence', 'Eilat 91, Tel Aviv', 3, 296);
INSERT INTO building VALUES (254, 'Golda Residence', 'Yehuda Halevi 81, Beersheba', 2, 202);
INSERT INTO building VALUES (255, 'Carmel Residence', 'Derech Hevron 71, Jerusalem', 2, 109);
INSERT INTO building VALUES (256, 'Shamir Hall', 'King George 68, Tel Aviv', 5, 207);
INSERT INTO building VALUES (257, 'Negev Hall', 'Moriah 37, Tel Aviv', 4, 156);
INSERT INTO building VALUES (258, 'Carmel Residence', 'King George 23, Haifa', 3, 397);
INSERT INTO building VALUES (259, 'Rabin House', 'Derech Hevron 16, Jerusalem', 5, 3);
INSERT INTO building VALUES (260, 'Shamir Hall', 'Rothschild 76, Tel Aviv', 4, 390);
INSERT INTO building VALUES (261, 'Einstein Lodge', 'Shlomtzion HaMalka 81, Beersheba', 3, 93);
INSERT INTO building VALUES (262, 'Shaked Hall', 'Begin 52, Beersheba', 2, 382);
INSERT INTO building VALUES (263, 'Carmel Residence', 'Allenby 95, Jerusalem', 5, 305);
INSERT INTO building VALUES (264, 'Jerusalem Heights', 'Yitzhak Rambo 21, Jerusalem', 5, 229);
INSERT INTO building VALUES (265, 'Negev Hall', 'Derech Hevron 73, Jerusalem', 3, 138);
INSERT INTO building VALUES (266, 'Ben Gurion Towers', 'Herzl 79, Haifa', 4, 384);
INSERT INTO building VALUES (267, 'Shaked Hall', 'Henrietta Szold 98, Jerusalem', 4, 54);
INSERT INTO building VALUES (268, 'Golda Residence', 'HaYarkon 3, Beersheba', 2, 336);
INSERT INTO building VALUES (269, 'Rabin House', 'Emek Refaim 72, Haifa', 2, 185);
INSERT INTO building VALUES (270, 'Shaked Hall', 'Ibn Gabirol 5, Haifa', 3, 145);
INSERT INTO building VALUES (271, 'The Arava Tower', 'Shlomtzion HaMalka 54, Jerusalem', 3, 218);
INSERT INTO building VALUES (272, 'Einstein Lodge', 'Jabotinsky 62, Tel Aviv', 2, 305);
INSERT INTO building VALUES (273, 'Jerusalem Heights', 'Dizengoff 61, Tel Aviv', 5, 295);
INSERT INTO building VALUES (274, 'Galilee Residence', 'Yehuda Halevi 21, Haifa', 2, 111);
INSERT INTO building VALUES (275, 'Shaked Hall', 'HaPalmach 43, Beersheba', 5, 318);
INSERT INTO building VALUES (276, 'Rabin House', 'Rothschild 12, Tel Aviv', 4, 138);
INSERT INTO building VALUES (277, 'Shamir Hall', 'Shlomtzion HaMalka 70, Tel Aviv', 5, 390);
INSERT INTO building VALUES (278, 'Golda Residence', 'Emek Refaim 75, Beersheba', 3, 108);
INSERT INTO building VALUES (279, 'Shamir Hall', 'Begin 64, Tel Aviv', 4, 391);
INSERT INTO building VALUES (280, 'Galilee Residence', 'Ben Yehuda 13, Haifa', 5, 191);
INSERT INTO building VALUES (281, 'Negev Hall', 'Weizmann 94, Haifa', 2, 277);
INSERT INTO building VALUES (282, 'Golda Residence', 'Derech Hevron 78, Tel Aviv', 3, 230);
INSERT INTO building VALUES (283, 'Ben Gurion Towers', 'Begin 10, Tel Aviv', 4, 395);
INSERT INTO building VALUES (284, 'Galilee Residence', 'Yigal Alon 35, Jerusalem', 5, 53);
INSERT INTO building VALUES (285, 'Ben Gurion Towers', 'Yitzhak Rambo 19, Jerusalem', 5, 19);
INSERT INTO building VALUES (286, 'Shamir Hall', 'Allenby 69, Beersheba', 4, 58);
INSERT INTO building VALUES (287, 'The Arava Tower', 'Sokolov 89, Jerusalem', 4, 15);
INSERT INTO building VALUES (288, 'Einstein Lodge', 'Ben Gurion 58, Tel Aviv', 5, 92);
INSERT INTO building VALUES (289, 'Einstein Lodge', 'Herzl 96, Beersheba', 4, 320);
INSERT INTO building VALUES (290, 'Weizmann Hall', 'Rothschild 4, Jerusalem', 2, 19);
INSERT INTO building VALUES (291, 'Shaked Hall', 'Emek Refaim 67, Beersheba', 2, 50);
INSERT INTO building VALUES (292, 'Shaked Hall', 'Allenby 10, Tel Aviv', 5, 190);
INSERT INTO building VALUES (293, 'Negev Hall', 'HaYarkon 94, Tel Aviv', 3, 392);
INSERT INTO building VALUES (294, 'Negev Hall', 'Sokolov 45, Tel Aviv', 3, 124);
INSERT INTO building VALUES (295, 'Ben Gurion Towers', 'Ibn Gabirol 52, Tel Aviv', 5, 9);
INSERT INTO building VALUES (296, 'Golda Residence', 'Ben Yehuda 64, Haifa', 3, 182);
INSERT INTO building VALUES (297, 'Herzl Residence', 'Dizengoff 67, Tel Aviv', 3, 100);
INSERT INTO building VALUES (298, 'Einstein Lodge', 'Ibn Gabirol 19, Haifa', 5, 297);
INSERT INTO building VALUES (299, 'Carmel Residence', 'Jaffa 26, Jerusalem', 4, 27);
INSERT INTO building VALUES (300, 'Einstein Lodge', 'Rager Boulevard 46, Haifa', 2, 373);
INSERT INTO building VALUES (301, 'Rabin House', 'Arlozorov 14, Tel Aviv', 5, 337);
INSERT INTO building VALUES (302, 'Carmel Residence', 'Arlozorov 50, Haifa', 5, 63);
INSERT INTO building VALUES (303, 'Negev Hall', 'Jabotinsky 26, Beersheba', 2, 35);
INSERT INTO building VALUES (304, 'Golda Residence', 'Weizmann 94, Haifa', 4, 81);
INSERT INTO building VALUES (305, 'Jerusalem Heights', 'Ben Gurion 52, Tel Aviv', 5, 297);
INSERT INTO building VALUES (306, 'Einstein Lodge', 'Yigal Alon 92, Jerusalem', 4, 325);
INSERT INTO building VALUES (307, 'Weizmann Hall', 'Yigal Alon 59, Haifa', 4, 370);
INSERT INTO building VALUES (308, 'Peres House', 'King George 18, Tel Aviv', 2, 348);
INSERT INTO building VALUES (309, 'Shaked Hall', 'Moriah 74, Tel Aviv', 4, 389);
INSERT INTO building VALUES (310, 'Golda Residence', 'Rager Boulevard 28, Jerusalem', 5, 215);
INSERT INTO building VALUES (311, 'Galilee Residence', 'Allenby 89, Haifa', 3, 183);
INSERT INTO building VALUES (312, 'Weizmann Hall', 'King George 33, Jerusalem', 4, 326);
INSERT INTO building VALUES (313, 'Golda Residence', 'Ben Gurion 17, Jerusalem', 4, 132);
INSERT INTO building VALUES (314, 'The Arava Tower', 'Derech Hevron 66, Beersheba', 2, 393);
INSERT INTO building VALUES (315, 'Carmel Residence', 'King George 74, Tel Aviv', 3, 395);
INSERT INTO building VALUES (316, 'Jerusalem Heights', 'Weizmann 56, Jerusalem', 3, 124);
INSERT INTO building VALUES (317, 'Shaked Hall', 'Moriah 23, Haifa', 5, 221);
INSERT INTO building VALUES (318, 'Jerusalem Heights', 'Arlozorov 23, Haifa', 3, 156);
INSERT INTO building VALUES (319, 'Shamir Hall', 'Henrietta Szold 5, Jerusalem', 3, 255);
INSERT INTO building VALUES (320, 'Weizmann Hall', 'Hertzel 55, Beersheba', 5, 108);
INSERT INTO building VALUES (321, 'Negev Hall', 'Arlozorov 19, Tel Aviv', 4, 247);
INSERT INTO building VALUES (322, 'Jerusalem Heights', 'Emek Refaim 85, Haifa', 4, 4);
INSERT INTO building VALUES (323, 'Peres House', 'Eilat 14, Beersheba', 4, 52);
INSERT INTO building VALUES (324, 'Technion Heights', 'Yitzhak Rambo 52, Beersheba', 2, 83);
INSERT INTO building VALUES (325, 'Technion Heights', 'Eilat 17, Haifa', 4, 13);
INSERT INTO building VALUES (326, 'Golda Residence', 'Sokolov 67, Jerusalem', 2, 353);
INSERT INTO building VALUES (327, 'Weizmann Hall', 'Ben Yehuda 4, Tel Aviv', 5, 11);
INSERT INTO building VALUES (328, 'Negev Hall', 'Allenby 41, Tel Aviv', 4, 124);
INSERT INTO building VALUES (329, 'Negev Hall', 'Ben Gurion 37, Beersheba', 3, 295);
INSERT INTO building VALUES (330, 'Shamir Hall', 'HaPalmach 36, Tel Aviv', 4, 230);
INSERT INTO building VALUES (331, 'Technion Heights', 'HaPalmach 78, Haifa', 3, 200);
INSERT INTO building VALUES (332, 'Carmel Residence', 'HaPalmach 20, Tel Aviv', 4, 234);
INSERT INTO building VALUES (333, 'Negev Hall', 'Jaffa 40, Jerusalem', 5, 165);
INSERT INTO building VALUES (334, 'Rabin House', 'Emek Refaim 68, Tel Aviv', 3, 252);
INSERT INTO building VALUES (335, 'Jerusalem Heights', 'Arlozorov 29, Haifa', 4, 190);
INSERT INTO building VALUES (336, 'Jerusalem Heights', 'Derech Hevron 57, Beersheba', 4, 198);
INSERT INTO building VALUES (337, 'Herzl Residence', 'Jabotinsky 34, Beersheba', 5, 306);
INSERT INTO building VALUES (338, 'Shaked Hall', 'Sokolov 29, Jerusalem', 3, 305);
INSERT INTO building VALUES (339, 'Jerusalem Heights', 'King George 40, Jerusalem', 5, 36);
INSERT INTO building VALUES (340, 'Ben Gurion Towers', 'Eilat 62, Beersheba', 2, 338);
INSERT INTO building VALUES (341, 'The Arava Tower', 'Agron 86, Jerusalem', 4, 331);
INSERT INTO building VALUES (342, 'Herzl Residence', 'Ben Gurion 73, Tel Aviv', 2, 390);
INSERT INTO building VALUES (343, 'The Arava Tower', 'Begin 87, Jerusalem', 5, 58);
INSERT INTO building VALUES (344, 'Herzl Residence', 'Jabotinsky 72, Tel Aviv', 3, 308);
INSERT INTO building VALUES (345, 'Einstein Lodge', 'Yigal Alon 63, Beersheba', 2, 29);
INSERT INTO building VALUES (346, 'Rabin House', 'HaPalmach 2, Beersheba', 5, 147);
INSERT INTO building VALUES (347, 'Shamir Hall', 'Henrietta Szold 59, Haifa', 5, 60);
INSERT INTO building VALUES (348, 'Golda Residence', 'King George 32, Haifa', 3, 385);
INSERT INTO building VALUES (349, 'Technion Heights', 'HaMasger 98, Jerusalem', 2, 284);
INSERT INTO building VALUES (350, 'Herzl Residence', 'Kaplan 84, Tel Aviv', 2, 308);
INSERT INTO building VALUES (351, 'Negev Hall', 'Herzl 91, Jerusalem', 3, 146);
INSERT INTO building VALUES (352, 'Technion Heights', 'Jabotinsky 4, Beersheba', 2, 170);
INSERT INTO building VALUES (353, 'Jerusalem Heights', 'Henrietta Szold 80, Jerusalem', 3, 312);
INSERT INTO building VALUES (354, 'Shaked Hall', 'Arlozorov 63, Haifa', 5, 253);
INSERT INTO building VALUES (355, 'Carmel Residence', 'Herzl 94, Beersheba', 4, 318);
INSERT INTO building VALUES (356, 'Jerusalem Heights', 'Yitzhak Rambo 16, Haifa', 5, 195);
INSERT INTO building VALUES (357, 'The Arava Tower', 'Yehuda Halevi 27, Beersheba', 5, 194);
INSERT INTO building VALUES (358, 'Peres House', 'Allenby 12, Beersheba', 2, 262);
INSERT INTO building VALUES (359, 'The Arava Tower', 'HaYarkon 55, Beersheba', 2, 169);
INSERT INTO building VALUES (360, 'The Arava Tower', 'Ben Yehuda 19, Tel Aviv', 2, 171);
INSERT INTO building VALUES (361, 'Galilee Residence', 'Kaplan 78, Jerusalem', 5, 285);
INSERT INTO building VALUES (362, 'Shamir Hall', 'Allenby 22, Tel Aviv', 4, 166);
INSERT INTO building VALUES (363, 'Peres House', 'Yitzhak Rambo 98, Jerusalem', 4, 244);
INSERT INTO building VALUES (364, 'Negev Hall', 'Shlomtzion HaMalka 76, Jerusalem', 4, 232);
INSERT INTO building VALUES (365, 'Shaked Hall', 'Yitzhak Rambo 76, Jerusalem', 5, 196);
INSERT INTO building VALUES (366, 'The Arava Tower', 'Weizmann 7, Tel Aviv', 4, 198);
INSERT INTO building VALUES (367, 'Einstein Lodge', 'Shlomtzion HaMalka 80, Beersheba', 4, 73);
INSERT INTO building VALUES (368, 'Shamir Hall', 'Henrietta Szold 25, Beersheba', 3, 176);
INSERT INTO building VALUES (369, 'Rabin House', 'Ibn Gabirol 4, Jerusalem', 5, 243);
INSERT INTO building VALUES (370, 'Carmel Residence', 'Ibn Gabirol 34, Beersheba', 3, 237);
INSERT INTO building VALUES (371, 'Einstein Lodge', 'Henrietta Szold 73, Jerusalem', 5, 242);
INSERT INTO building VALUES (372, 'Carmel Residence', 'Begin 42, Haifa', 5, 262);
INSERT INTO building VALUES (373, 'Weizmann Hall', 'Moriah 64, Jerusalem', 2, 308);
INSERT INTO building VALUES (374, 'Jerusalem Heights', 'Weizmann 89, Haifa', 5, 31);
INSERT INTO building VALUES (375, 'Shamir Hall', 'Shlomtzion HaMalka 18, Haifa', 3, 378);
INSERT INTO building VALUES (376, 'Golda Residence', 'Weizmann 80, Jerusalem', 5, 175);
INSERT INTO building VALUES (377, 'Einstein Lodge', 'HaMasger 44, Tel Aviv', 3, 1);
INSERT INTO building VALUES (378, 'Shaked Hall', 'Herzl 41, Jerusalem', 5, 291);
INSERT INTO building VALUES (379, 'Herzl Residence', 'Derech Hevron 89, Tel Aviv', 2, 329);
INSERT INTO building VALUES (380, 'Weizmann Hall', 'Eilat 20, Beersheba', 4, 129);
INSERT INTO building VALUES (381, 'The Arava Tower', 'Shlomtzion HaMalka 23, Haifa', 5, 62);
INSERT INTO building VALUES (382, 'Jerusalem Heights', 'Jaffa 80, Tel Aviv', 5, 284);
INSERT INTO building VALUES (383, 'Negev Hall', 'Sokolov 83, Tel Aviv', 5, 74);
INSERT INTO building VALUES (384, 'Galilee Residence', 'HaPalmach 36, Tel Aviv', 2, 180);
INSERT INTO building VALUES (385, 'Galilee Residence', 'Rager Boulevard 57, Jerusalem', 3, 153);
INSERT INTO building VALUES (386, 'Carmel Residence', 'Yitzhak Rambo 23, Jerusalem', 2, 267);
INSERT INTO building VALUES (387, 'Golda Residence', 'Jabotinsky 90, Beersheba', 3, 290);
INSERT INTO building VALUES (388, 'Weizmann Hall', 'Kaplan 7, Haifa', 3, 162);
INSERT INTO building VALUES (389, 'Einstein Lodge', 'Rothschild 70, Haifa', 5, 124);
INSERT INTO building VALUES (390, 'Rabin House', 'HaMasger 40, Jerusalem', 4, 376);
INSERT INTO building VALUES (391, 'Carmel Residence', 'Ibn Gabirol 51, Tel Aviv', 3, 219);
INSERT INTO building VALUES (392, 'Shamir Hall', 'Jabotinsky 20, Beersheba', 2, 144);
INSERT INTO building VALUES (393, 'Shaked Hall', 'Derech Hevron 18, Tel Aviv', 5, 360);
INSERT INTO building VALUES (394, 'Ben Gurion Towers', 'Yitzhak Rambo 59, Jerusalem', 3, 222);
INSERT INTO building VALUES (395, 'Golda Residence', 'Weizmann 3, Beersheba', 4, 78);
INSERT INTO building VALUES (396, 'Carmel Residence', 'Yigal Alon 87, Haifa', 4, 156);
INSERT INTO building VALUES (397, 'Weizmann Hall', 'Jabotinsky 53, Haifa', 2, 89);
INSERT INTO building VALUES (398, 'The Arava Tower', 'King George 60, Jerusalem', 5, 262);
INSERT INTO building VALUES (399, 'Herzl Residence', 'Hertzel 14, Beersheba', 2, 41);
INSERT INTO building VALUES (400, 'Galilee Residence', 'Dizengoff 50, Tel Aviv', 3, 208);
